### ISSUE TITLE
Amending Search and filter behaviour

### ISSUE THREAD

**Issue by marinacastejon** [canonical/vanilla-framework#4076]
## Pattern to amend
Amendment proposal regarding the behaviour of the Search and filter component when the user removes the filter. Currently the panel opens. 

## Visual
![137158310-2f78b7f3-51da-4c39-bf13-99c6e822b428.gif](https://images.zenhubusercontent.com/61309e789df65d8124887eac/edc79b4f-944b-4705-8b92-f295f06e8db3)

## Context

[See this issue](https://app.zenhub.com/workspaces/-vanilla-squad-59438c953747487777fbe484/issues/canonical-web-and-design/react-components/621).

We have a specific case to cover in the new Hiring Dashboards that will be used by all Canonical employees participating in hiring activities. My hypothesis is that this will not be a corner case but that it is quite a standard behaviour that could benefit other Canonical UIs. 
Need: remove filters easily. Re-opening the panel when a user tries to remove the filters is unnecessary IMO. 

Steps for the user: 
- Search for a specific item in a list either by browsing a list or by typing
- Select this item
- Filter results based on their selection
- Remove the filter easily without re-opening a panel (because it would be an extra unnecessary step for them)

The reasons why the split search and filter is far from optimal in this case:
The search query is directly linked to the elements that appear as checkboxes, it does not makes a lot of sense the keep
them visually separated.
Some users might have 50 items on the list, making it very inconvenient to have a collapsed list of checkboxes
We want to minimise the space, since most users won't probably filter (hypothesis based on research), so having a filter
list always visible on the left of the graph will take up more space than deserved.

**Comment by clagom** [comment]
- The current implementation of the component didn't take into consideration the UX specs: https://discourse.ubuntu.com/t/behaviour-delete-a-filter-chip/21546
In particular:
- The input field should include chips (currently in a different container, separated from the input field)
- Users should be able to use backspace to remove chips (currently is not possible because of the separation of the elements)
- If the focus is on the input field, it should open the panel underneath
- If there's no focus on the input field, the panel shouldn't open
- Clicking with the cursor on the "X" to remove a chip from the input field shouldn't therefore trigger the panel to open

WG: please refer to the UX specifications in order to iterate on the implementation of the component.
CC @bartaz @sowasred2012
