### ISSUE TITLE
Make col-6 work as col-medium-3 on medium breakpoint?

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4690]
@carkod suggested this is a default on bootstrap and sounds like an interesting idea. What do you think?

**Comment by bartaz** [comment]
To be honest I did initially think it should work this way myself as well.

But it leads to some questions:
- should it only happen on medium? why not on small as well?
- why should it happen only to col-6 and not others?
- introducing it would potentially be a breaking change (if it starts to use half grid layout when it wasn't expected)

It would be quite a weird precedent to have only `col-6` behave differently from the others. And technically we can't do it for others, because we can't easily map all of the other 12 sizes to 6 columns on medium, or 4 on small screens.

Do do that we would need to introduce specific `col-half` or something like this, that clearly doesn't specify column count and can semantically mean half of grid on any screen size.

**Comment by carkod** [comment]
Yeah, I think this is more up to design. If designs will consistently be for only `col-6` -> `col-medium-half` but if we want to keep flexibility then of course that would not work. Same with others, the way I saw it in my page build it was more a matter of keeping up with design.

**Comment by bartaz** [comment]
I think we are properly addressing this with new grid components with 25% split. We don't need to amend the legacy grid at the moment.
