### ISSUE TITLE
Remove round corners from chips

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4709]
The branding direction is to remove rounded corners, can we please do so on the chips.

**Comment by bartaz** [comment]
This seems to contradict a lot of discussions we had before on that. It practially makes chips look like labels again.
Also chips traditionally have rounded sides like this, that's why they are called chips. Having square "chips" in things like search and filter may look very confusing.

Should it at least be tested and go through design review or working group?

Feels to me to big of a change to just drop it into code.

**Comment by lyubomir-popov** [comment]
I'm worried about this as well - the new things look like buttons... maybe we can try other shapes like the price tag shape used somewhere.

**Comment by bartaz** [comment]
@lyubomir-popov Not sure if it's a topic for working group, or design assembly, but seems it would be good to have some discussion around it to understand what are the concerns about current style and how to fix it.

**Comment by danielmutis** [comment]
Arguments against:
1. Would we make radio buttons also have sharp corners?
2. They are hard to distinguish when they are lined up next to each other, for example on search and filter. 
3. Users could be familiar with chips having rounded corners, which could cause confusion. 
4. It is a good way to distinguish them from buttons. Could be confusing in the use case of search fields.

**Comment by lyubomir-popov** [comment]
Discussed in the Visual design meeting and we agreed this is causing issues, so closing.
