### ISSUE TITLE
Nav items on-hover effect is too large 

### ISSUE THREAD

**Issue by petesfrench** [canonical/vanilla-framework#4712]
**Describe the bug**

The on hover effect on top nav items on medium screens is bigger than the original item

**To Reproduce**

1. Go to ubuntu.com
2. Change screen size to medium
3. Hover mouse over nav item
4. See the on hover effect is too large

**Expected behavior**

For the on hover affect not to be larger than the original item

**Screenshots**

![image](https://user-images.githubusercontent.com/58276363/226967766-b44033fd-6027-47f9-a0aa-4d7d2fdf353f.png)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome

**Comment by bartaz** [comment]
@petesfrench Thanks, but this doesn't look like Vanilla navigation. It seems to be ubuntu.com custom styling.

On Vanilla we never show top menu items in multiple lines. If they don't fit on screen in one line they should become a mobile dropdown.
Ubuntu is different in this case because of it's mega menu.
