### ISSUE TITLE
Nesting dark strip within a dark strip with an imafge background causes problems 

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4724]
This is thinking out loud for the 4.0 release - we need strips or whatever component we decide to call it that do not set colours - just add shallow, regular or deep (emphasis) space. Currently, when I try to do that as in the example below, the background gets in the way:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/2741678/229505469-144e5898-3353-448f-af99-2ac8b56cefdf.png">

**Comment by bartaz** [comment]
Why is a strip used here at all? Shouldn't the spacing come from heading itself?
We will have spacing utils, so maybe they would help?

Would it work if you use just `p-strip`? I think it should not change either background or text color.

**Comment by lyubomir-popov** [comment]
p-strip here makes the whole thing white on white - try it.

**Comment by bartaz** [comment]
I guess this is one of the reasons why strips should not be nested, and were not meant to be nested. 

For 4.0 we are going to have separate component to provide bottom spacing on containers (https://github.com/canonical/vanilla-framework/pull/4730). This new component should be used instead of nested strips, and strips would be reserved to their original purpose - providing a background for the whole width of the page.

**Comment by anthonydillon** [comment]
In this example, it definitely looks like the heading should provide the space here.

**Comment by lyubomir-popov** [comment]
Works for me. Maybe a class on headings that simply adds shallow, deep or regular space underneath?

**Comment by bartaz** [comment]
Closing this, we introduced new section/block components that should resolve issues like this.
Strips should not be nested.
