### ISSUE TITLE
Utility or class to add .5rem margin-top on images

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4791]
We often need a space above the image (only the image) in layouts like these:

![image](https://github.com/canonical/vanilla-framework/assets/2741678/ef49af45-25f7-45e1-a566-f6d07a7b1f67)

We have this locally in c.com, would be nice to have it documented and upstreamed to vanilla:

`.p-image-wrapper {
  padding-top: $spv--small;
}
`

**Comment by bartaz** [comment]
This one bugs me a lot and I don't know how to approach it.

Creating a component for that purpose sounds weird. A utility/modifier on images may be a workaround, we have couple `p-image--something` class names currently (although by the look of them, they will be dropped soon). 

The issue I see is that this "top padding" is not really part of the image, it should be part of the rule component because it comes from it and it's a bit counterintuitive that instead of rule having bottom margin, we force some elements (only images?) after it to add top margin (that we don't use anywhere else).

I experimented before with adding top margin to all images but this obviously causes some issues (especially when small images are used in lists, etc).

**Comment by bartaz** [comment]
@lyubomir-popov maybe a stupid question, but why do text elements have it built-in? Maybe we could remove it from text elements (move them up 0.5rem, so they will still be on the baseline) and then the rule component can simply have bottom margin?

**Comment by bartaz** [comment]
I understand that it's "next to no effort" to add a class name or a wrapper element to an image. The issue is that there is no nice way to implement it within a design system.

It's not a good component, because it's only purpose is to nudge an image couple pixels down.
It's not a good util, because it only makes sense for images.

So maybe it's a "variant" class name on an image. But will it only be images?

You mentioned @lyubomir-popov other block components that may need that. Are there any examples? I guess I've seen cards under horizontal rule, anything else may go there? Would other components have such "nudge" built in, or would they need an option for it as well?

**Comment by lyubomir-popov** [comment]
applies to videos as well. not necessarily images only

**Comment by danielmutis** [comment]
@lyubomir-popov to provide design guidelines for these spacing rules. Further discussion with @bartaz

**Comment by bartaz** [comment]
Scope:

We could implement it as a new component called "media container", possibly as simple as:

```scss
.p-media-container {
   margin-top: $sp-unit;
}
```

It should be documented on Images page https://vanillaframework.io/docs/patterns/images.
An example should show an image wrapped in this new container placed under a rule component:

```html
<hr class="p-rule" />
<div class="p-media-container">
   <img … />
</div>
```

possibly should be mentioned on Rule component page, as it's mostly needed for situations when we place an image under a rule component (https://vanillaframework.io/docs/patterns/rule)
