### ISSUE TITLE
P-section/p-block: improve documentation

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4809]
The current use cases of p-section and p-block do not cover all cases where they are needed. 
[Here ](https://github.com/canonical/canonical.com/pull/910/files/8113612e4d8e30d3644810c1eca3d714fc76f77a#r1241966721) for example, @mtruj013 rightly pointed out that nesting p-sections is wrong according to the documentation. 

Another related issue - needing a p-section depending on context (volume of content in adjacent elements): https://github.com/canonical/vanilla-framework/issues/4797

I think the intuition is that a 64px margin-bottom is helpful when an element is followed by a large block of content which thus competes for attention with the current element. We need to add a few examples to clearly explain this in the documentation.

**Comment by bartaz** [comment]
@lyubomir-popov What is currently implemented and documented is how we initially discussed the use cases for this. Section component was supposed to be a top level wrapper on clear sections of the page and replace strip. If any additional sub-sections are needed they were supposed to be blocks. That's why sections were not supposed to be nested inside each other.

Now it seems we are again discussing allowing nesting of p-section, which in practice means using it as utility to add more space under arbitrary blocks of content. 

This is again going to be confusing to designers and developers. We are again suggesting that spacing doesn't come from component but is redefined case by case.

What kind of rules are there around spacing? Design system needs to reflect the way we want to design. I guess designers also need clear rules for when to use each spacing, right? It seems so vague right now that it's hard to not only implement it in code in precise and clear way, but even to document it.

**Comment by lyubomir-popov** [comment]
From a designer's perspective, the best way I can explain it is that spacing exists to modify the visual prominence of elements within the context in which they are used. I've provided an anecdotal example in this [issue](https://github.com/canonical/vanilla-framework/issues/4797). 

When preparing a mockup, a designer "weighs" the circumstances, and picks from a very limited palette of options (namely, 3: shallow 24, regular 64, deep 128).  This to me is the quickest and simplest way to communicate between a designer and developer. The documentation should then mainly focus on explaining how to obtain that space through examples. 

The documentation can try to provide some intuition, with examples and rationale, but this can quickly turn into a "boil the ocean" sort of endeavour - we can't reasonably list all situations when a given amount of space might be needed.

What we can also do is create components and variants, as you suggested in the headings issue  for example, for a takeover with 1 h1 and up to 10 words in a paragraph following it, use this default variant; but if the paragraph is closer to 50 words than 10, use this other variant".

**Comment by bartaz** [comment]
The way we implemented it is using container components, similar to strip.

So we have a "layout" container component that can take any content and has a defined spacing (strips, sections, blocks). In this model space between "elements" is a product of a container, not the content. Semantic structure of the page (how it is split into strips/sections or subsections=blocks) defines the spaces between elements.

From your description @lyubomir-popov it seems like from design point of view the semantic structure of the page doesn't matter. Spacing (and other aspects like heading types) are not defined by semantics or structure, but by visual alignment.

So can you say that when we have a page, it can be split into specific sections, each section having regular spacing, with possibly some sections highlighted by deep spacing? Or is it so completely content/context dependant that the structure doesn't matter? And standard or deep spacing can appear inside "sections" of the page? It sounds that rather than components having margins defined for them, we want "spacer" component. An empty block of given height that designer will choose to put in places.

**Comment by bartaz** [comment]
As discussed in today's meeting between me @ClementChaumel and @lyubomir-popov it seems that semantic section/block component are more misleading than helpful. In reality we need more flexibility.

We decided to deprecate section/block components and introduce a container component that will have 3 variants for default, shallow and deep spacing.

**Comment by bartaz** [comment]
Done in #4823
