### ISSUE TITLE
side navigation mobile z index issue with hrs

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4816]
From @juanruitina 

One comment: even if it won't be a problem here, I see separators have z-index: 2; as a result, on mobile they show on top of the side navigation with a very awkward result. Just flagging it up in case this has to be addressed on Vanilla.

![Screen Shot 2023-06-29 at 19 09 56](https://github.com/canonical/canonical.com/assets/1409729/a12afb04-6a30-4514-ba5d-608c563cd969)

**Comment by bartaz** [comment]
I've seen similar issue with z-index of HR conflicting with some dropdown before.

I have no idea why we have z-index on HRs, it must be a legacy thing. We can just try to drop it, but I don't know what it was trying to solve.

**Comment by lyubomir-popov** [comment]
what does git blame say?

**Comment by bartaz** [comment]
https://github.com/canonical/vanilla-framework/blob/08bf23fc13baf931d32b5cc1b414c5eed91b9234/scss/_base_placeholders.scss#L199C2-L205C4

So it's about "u-no-margin--bottom". Because HR without margin has negative bottom margin, we set z-index, so that (as far as I understand) it's not covered by next element that is pulled up.
And because `p-rule` component is equivalent of `hr.u-no-margin--bottom` it has that by default.

Talking about this specific bug, I'm surprised that side navigation doesn't have z-index of it's own…

**Comment by bartaz** [comment]
Where does it happen? Side navigation seems to have z-index of 102, so should work just fine.

**Comment by lyubomir-popov** [comment]
@bartaz @juanruitina reported it here https://github.com/canonical/canonical.com/pull/907#issuecomment-1613535207

**Comment by bartaz** [comment]
I don't see anything wrong there myself:

<img width="779" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/ac7f6311-78ee-4e3f-b958-082651bfbf2f">

Until confirmed that it is a bug in Vanilla and not local issue, let's keep the discussion there on the PR maybe.

**Comment by bartaz** [comment]
Thanks, I was able to reproduce it.

It seems to be caused by local canonical.com styles:

https://github.com/canonical/canonical.com/blob/a45d30608e3b74a73d9d58305023e9cc58de82dd/static/sass/styles.scss#L351-L354
