### ISSUE TITLE
P-breadcrumbs: add margin-bottom

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4818]
## Pattern to amend

`p-breadcrumbs`

## Visual

Currently, the breadcrumbs have no margin bottom, so the element that comes after sits too close to them:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/8bee61a1-8bfe-464a-9cc6-322f6bd1ede2)

I propose adding .5rem at the bottom, to improve the way it looks:
![image](https://github.com/canonical/vanilla-framework/assets/2741678/0cabc00a-d6d4-4a90-8747-fbda351510cf)

**Comment by bartaz** [comment]
Currently breadcrumbs seem to have 1.5rem margin (indirectly from a `<ol>` list inside of them). Which seems like a bug I guess.

<img width="549" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/cf3eb2b7-bbc3-4da6-8f3b-4655e703bc84">


So we want breadcrumbs to ignore default list margins, and only have 0.5rem margin by themselves?

**Comment by ClementChaumel** [comment]
Actually, the issue is a side effect from using `p-text--small-caps` on the `p-breadcrumbs__items` reducing its bottom margin to .5rem instead of 1.5rem. A change that would make more sense here is to use the `p-text--small-caps` text style by default on the breadcrumbs so there's no need to use the two clashing classes
