### ISSUE TITLE
p-navigaton logo to use svg assets instead of markup

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical/vanilla-framework#4831]
## Pattern to amend

The brand team has asked that we switch from markup-based logos to actual svg assets, as it is not possible to fine tune subtle spacing aspects with the markup-based version. 

Can we please schedule this for implementation?

cc @bartaz

**Comment by bartaz** [comment]
There are couple of issues I see with that, that we would need to find solutions for:

- it will mean that every smallest website/tool that uses Vanilla will have their logo created manually as SVG. Right now with text we can quickly put up any small product or website with new style of the logo. Without that all these will be needing VD to create an asset specifically for them.

- even in the basic version of top nav we have 2 sizes of logo (not just scaled up). On medium/small navigation is smaller and therefor logo tag has less height:

<img width="1034" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/d32cb79b-0147-434c-9b6d-f8353e36876c">

<img width="939" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/9db058ec-ce96-4492-afc9-1a9b2964732d">

- for application logo we will need a version with separate logo tag and text to be able to collapse the sidebar. This is not currently implemented with new logos in Vanilla, but some apps are already implementing it themselves because they need it. With markup logo it's quite trivial to hide part of it. With SVG it will again mean that very specific assets will need to be crated for any app.

![app-logo](https://github.com/canonical/vanilla-framework/assets/83575/c87109c3-2fc9-446d-9812-76350621e64b)

**Comment by lyubomir-popov** [comment]
I know, it will be highly labour-intensive, and we've discussed that. Unfortunately, there's no other way to do it as all the subtle kerning wokr done by Brand is lost when we use plain text. It will be even more laborious on u.c, where every bubble's name is positioned as a logotype, so we will need hundreds of logos for u.com alone. And every time a new bubble is added, creating a logo for it will become a dependancy.

**Comment by bartaz** [comment]
We can't just remove current solution anyway, so at least for some time both will have to live side by side. So text based logo may be used until the SVG is provided for example.

Maybe we would be able to accept text logo in applications as well to avoid spliting SVG into two parts.

**Comment by bartaz** [comment]
Triage: this is high effort (both in terms of design providing all the logos, and in terms of implementation).

Do we still need it? Is the HTML implementation close enough so it could stay?
Needs discussion in relation to how to address this in new architecture (if at all).

**Comment by bartaz** [comment]
@lyubomir-popov Do we still want to use SVGs instead of HTML-based logos?

**Comment by lyubomir-popov** [comment]
I think we can close it. I believe @jmuzina worked on improving the non-svg version, and it looks ok to me:
![image](https://github.com/user-attachments/assets/a8ed2089-66c6-4bbc-8f74-19c29cb43f7f)
