### ISSUE TITLE
Height mismatch between search box and search and filter

### ISSUE THREAD

**Issue by lorumic** [canonical/vanilla-framework#4984]
**Describe the bug**

In the current implementation, due to the spacing around the search icon (which is present only in the search box), the search box has bigger height than the search and filter (1px difference). See screenshots below.

**To Reproduce**

This can be easily checked by inspecting the examples on the VF website docs (as shown in the screenshots below).

**Expected behavior**

Ideally, both components should have the exact same height. So that when we have a mix of them in different pages of our app, and they're always in the same position of the page, we don't see a 1px "jump" when switching pages.

**Screenshots**

- Search box:

![image](https://github.com/canonical/vanilla-framework/assets/56583786/3dd6ddd9-6339-4cfa-80fb-a580faaf4c06)

- Search and filter:

![image](https://github.com/canonical/vanilla-framework/assets/56583786/d3649df7-5518-4c76-9c3a-aadcb26fbf44)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser: Google Chrome
- Version: 121.0.6167.160

**Comment by bartaz** [comment]
The issue seems to still be there. If you put search box component side by side the search and filter there is a 1px difference.

<img width="886" alt="image" src="https://github.com/canonical/vanilla-framework/assets/83575/f6a32a50-57be-4638-9b43-ffcf160a7eac">

I'm not certain, but possibly there is a miscalculation here:
https://github.com/canonical/vanilla-framework/blob/d4a5eb68e7c12aa6b6ddf58bbf490c09cc3e4f9d/scss/_patterns_search-and-filter.scss#L22

This may need to be corrected to include the values from https://github.com/canonical/vanilla-framework/blob/d4a5eb68e7c12aa6b6ddf58bbf490c09cc3e4f9d/scss/_base_forms.scss#L24-L38 input, so take the same line height, paddings and a single border.

**Comment by lorumic** [comment]
> The issue seems to still be there. If you put search box component side by side the search and filter there is a 1px difference.

Hey @bartaz - I think you wanted to post this comment in the [PR](https://github.com/canonical/vanilla-framework/pull/5019). This is the issue :)

**Comment by bartaz** [comment]
> > The issue seems to still be there. If you put search box component side by side the search and filter there is a 1px difference.
> 
> Hey @bartaz - I think you wanted to post this comment in the [PR](https://github.com/canonical/vanilla-framework/pull/5019). This is the issue :)

Ah, yes, I don't know how this happened. I must have clicked a wrong link.

**Comment by bartaz** [comment]
Triage: a bug in current codebase, hopefully not a large effort (although may be not low as well). There was an attempt in PR, we could have a look what needs to be addressed there.
