### ISSUE TITLE
Add left and right chevrons to vanilla icon set

### ISSUE THREAD

**Issue by camillet16** [canonical/vanilla-framework#5066]
A component in Vanilla needs to be flexible enough that it can be used across a wide range of scenarios and shouldn't be constrained to a specific number of applications.

## Visual

<img width="387" alt="Screenshot 2024-04-24 at 4 29 14 PM" src="https://github.com/canonical/vanilla-framework/assets/112855834/691c720b-a291-4cd0-9adf-95a67d5022d2">

## Context

at the moment we're using rotated up and down buttons. It's being used across multiple products

## State

The same states as other vanilla. icons

## Progressive enhancement

since it's an icon it works across all screens

**Comment by camillet16** [comment]
@bartaz we do have them i'll upload them onto the assets

**Comment by bartaz** [comment]
@camillet16 for Vanilla they don't need to be in assets, as we inline them in CSS.

Are there in icons drive folder (could you link those)? Or add them to comment here, and I can use the files to add to Vanilla CSS.

**Comment by camillet16** [comment]
![chevron-left](https://github.com/canonical/vanilla-framework/assets/112855834/a30dce47-53f0-41eb-81f0-f6b7f582187e)
![chevron-right](https://github.com/canonical/vanilla-framework/assets/112855834/b7b6328b-2fce-4124-88e3-e472b09e2d57)


Here they are. I'm not sure if they're on a drive somewhere.

**Comment by jmuzina** [comment]
Is there a reason we would need to add new SVGs to the project for left/right chevrons instead of adding new left & right classes that perform the icon rotation (upstreaming the rotation work that some projects are doing)? 

VF currently uses a single SVG (pointing downward) for all chevrons:
https://github.com/canonical/vanilla-framework/blob/4109529d291740aa752b4e24967ef0d056d157ae/scss/_base_icon-definitions.scss#L13

Then it rotates according to applied class (example is for `p-icon--chevron-up`):
https://github.com/canonical/vanilla-framework/blob/4109529d291740aa752b4e24967ef0d056d157ae/scss/_patterns_icons.scss#L133

Here's a link to a proposed change that doesn't need any SVGs to be changed: https://github.com/canonical/vanilla-framework/blob/b2fcc7d17f682508d85c5f35e3bd12554aa7da98/scss/_patterns_icons.scss#L132

Otherwise, I think we'd need to re-implement the chevron icons slightly as the `vf-icon-chevron-themed` [mixin](https://github.com/canonical/vanilla-framework/blob/4109529d291740aa752b4e24967ef0d056d157ae/scss/_base_icon-definitions.scss#L21) uses the same SVG for all directions.
