### ISSUE TITLE
Examples toolbar hides bottom content of tall examples

### ISSUE THREAD

**Issue by jmuzina** [canonical/vanilla-framework#5283]
When viewing an example that is taller than the viewport (i.e. [forms combined](https://vanillaframework.io/docs/examples/patterns/forms/combined?theme=light)), the examples toolbar hides some content behind it.

<img width="374" alt="Screenshot 2024-08-07 at 1 05 42 PM" src="https://github.com/user-attachments/assets/6879888a-ee47-447a-b6b5-96304967c101">

This isn't a problem in Percy, as the toolbar is hidden for Percy tests. However it makes it hard to see what's behind the toolbar on a browser.

We should either adjust the page height to make room for the toolbar, or display the settings some other way (like a modal / aside).

**Comment by bartaz** [comment]
I noticed this as well when working with navigation.

In most cases (long content) adding some margin bottom on body would be sufficient, so you can scroll past this.
But in case of navigation on mobile, its position is fixed, so it won't help. 

Moving the toolbar to some other place also only partially solves the problem (it will still cover some part of the screen).

I guess we need some way to hide/toggle this toolbar.
A simpler approach would be to just allow closing it, and reload to make it reappear.
Because if we want to be able to really toggle it, there would still be a need for some "collapsed" view that can be expanded.
