### ISSUE TITLE
Give the skip link a more modern styling

### ISSUE THREAD

**Issue by lorumic** [canonical/vanilla-framework#5356]
## Component/pattern to amend

[Skip link](https://vanillaframework.io/docs/patterns/links#skip-link)

## Visual

Current appearance:

![image](https://github.com/user-attachments/assets/0c1b07b3-6ab8-4b3f-80c0-48ef2aca4aeb)

Proposed appearance (mostly about size and spacing, colours in this proposal can probably be improved):

![image](https://github.com/user-attachments/assets/12db803e-31ec-4929-8075-80a19683ffc4)

Competitors' appearance:

1. Jira:

![image](https://github.com/user-attachments/assets/914d9474-c852-414f-8f27-926d46840cc9)

2. GitHub:

![image](https://github.com/user-attachments/assets/4be5c5b5-f97f-48b0-91db-e91dc9364033)

## Context

The currently full-width, non-spaced skip to content link could benefit from a re-styling, to make it more modern and similar to the ones of competitor web applications (see the 2 examples shown above).

**Comment by danielmutis** [comment]
WG: We prefer how Jira has solved it, mainly because it is clear that the link is overlaying the logo. In the proposed solution it looks like the button is replacing the logo completely. 

It would be good to also consider other parts of the page to skip to, similar to Jira. For example, skipping to the side navigation or skipping to the content of the active page. 

@lorumic Could you maybe make a proposal which looks closer to Jira's?

**Comment by lorumic** [comment]
> @lorumic Could you maybe make a proposal which looks closer to Jira's?

Hey @danielmutis - sure thing. Proposal sent: #5371
